### PDL 

#### Yogeshwari--225229148

### Lab1 Python Functions and Numpy

##### Part-I: Write a method for sigmoid function

In [7]:
import math
import numpy as np

In [34]:
#1
def mysigmoid(x):
    s = 1. /(1+ math.exp(-x))
    return s


In [25]:
#2
print(mysigmoid(4))

0.9820137900379085


In [28]:
#3
x = np.array([1, 2, 3])
y = mysigmoid(x)

In [33]:
import pandas as pd
df=pd.DataFrame({"x": x,"mysigmoid(x)" : y})
df

x  mysigmoid(x)
0  1      0.731059
1  2      0.880797
2  3      0.952574

In [35]:
#4
def mysigmoid(x):
    s = 1. /(1+ np.exp(-x))
    return s

In [37]:
#5
x = np.array([1, 2, 3])
mysigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

#### Part-II: Gradient or derivative of sigmoid function

In [39]:
def sig_derivative(s):
    s=mysigmoid(x)
    ds=s*1-s
    return ds

In [42]:
sig_derivative(3)

array([0., 0., 0.])

#### Part-III: Write a method image_to_vector()

In [43]:
#1
def image2vector(image):
   
    v = image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)
    ### END CODE HERE ###
    
    return v

In [44]:
#2
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


##### Part-IV: Write a method normalizeRows()

In [45]:
def normalizeRows(x):
    x_norm = np.linalg.norm(x, ord = 2, axis = 1, keepdims = True)
    x = x / x_norm
    return x

In [47]:
x = np.array([
    [0, 3, 4],
    [2, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.26726124 0.80178373 0.53452248]]


##### Part-V: Multiplication and Vectorization Operations

In [57]:
#1
import time
x1 = [9, 2, 5]
x2 = [7, 2, 2]
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 77
 ----- Computation time = 0.0ms
elementwise multiplication = [63  4 10]
 ----- Computation time = 0.0ms


In [58]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")


dot = 278
 ----- Computation time = 0.0ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.0ms


##### Part-VI: Implement L1 and L2 loss functions

In [51]:
#1
def L1(ypred, y):
    loss = np.sum(abs(ypred - y))
    return loss

In [52]:
ypred = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(ypred,y)))

L1 = 1.1


In [54]:
#2
def L2(ypred, y):
    loss = np.dot(yhat - y, ypred - y)
    return loss

In [55]:
ypred = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(ypred,y)))

L2 = 0.43
